spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch_demo
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  batch:
    jdbc:
      initialize-schema: ALWAYS